travis:
  secure:
    BINSTAR_TOKEN: Bq+g5L0GiSCHvyy2NpWjaI4rbF9CSgXkcyTQVefCg/RIA0VaW7AlEpvaKuFZvPCf33nmqIRRNX7giGvbQWipONmj1zb0kV12nb2dhN/OZ8Da6Zbna/ynGVa4MuvIdWRbb+FJ0bGEuehggq6BuKNjRAcLpz4omzt7rKoF5KG9PEwNQvZH8M1ZCHk5KdwhmS2K1xk4L6WGTVEcGatc16btBb4Gc1Ix9qD1/QSAlEYo1WGr1tsEcAwDfV2htTSXnH5dL0LBLUzcLUvifFRUxUDMTxLk+sALxguPsoeqyO0jRFeQchV7KA0ZMS9lZk9L6FScTntPVHSR6OmS+ftcdrDdZJnJhpJwPTTNVYrC/V5kX1JrH+QBb/OtjmLyzxqWWva3StqMG3cKOdbQ/MPwdflcBeIdqaOXvFSGlNuoHywd4Iqd2wlUufzu1G8Fq2B5lEtTJ+QlUZfekrT4fCrPOntgOCAqhu9k4kYVE+QY37GSA+TQNt4LUGfEPH4cUkI+u3QTvuiXv6rPiVxsEDMgJONMYCzDhspPcTmjou6HHaxxqqKAHwp+pZbAOne+WT9tNbo9d3JBw92qEF5J+obg9Q+ugakIuidDCXIe689hFThWw6a7hAdaj8UUnEjE7vFMC4vic0Gf4O0si/1WzIAjAWRChMVkSTEShKqBn2Ri5NiJ4i0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
