travis:
  secure:
    BINSTAR_TOKEN: WBMSAkgNgcV/p1oaJqAIwN9VtPhu+EUZXCtslpMNf3D0o8bT2eqhi3zTSgw6TYk9JV7syW5vwQcqg7Ui7dPEuGdhm4FM4iUoVRDJMSwC7HAo8YEA97CX2CxrabwlaRtUmXz5OEzsGBr42cUkdxkdlKcvWAfWWPLudgtqEUY+23nPZkPpqjk28HU4RdIHg6SyCj8AYUtRelDWPONvky3XecJK+Jf5x+DAH14AjqLegV+kLJAIWC75GKzxv2uQLE1h16Yfua4SnP6Lnt+TujkEF7oY42vW5curoHxFz7wryKl7tJmuA7cmAFOymhubmtkz5vnB0OGENL0UgX9sNOwZv0rLqvP3tY3dCz13bkzcWj+uqcLkhmU1vhhZxvIl2Kj11VGIwZvegiDntbR2adP7/BQQb0kqFo47Vj/Mqf0hm9w7MZ43vHaP0K7Mf8gXpqu0qxjv9LNCYDMLmkP8a8lU8ljbhGlPVjhAFQRkZZcufTgAqJBlxcn3kgARrBD28QaWVhYZp4PA+oLnMJa+LPr0psJ6biHPKaSUB7wVpxEESC+qARDoljaRsphmOEHB8sytkYIwMKO76PyS0b/wwLxoBW5DZh7ymg650cCjNS0yejAPo3Shx7+08AKMKO67/EQFwobsPTilZ7Ca+IfoiCZhqP09nu1x6ELt8NW7VbClPbs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
